/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "active": {                 "en": "Active",                                          "de": "Aktiviert",                                       "ru": "Актив",                                           "pt": "Active",                                          "nl": "Active",                                          "fr": "Active",                                          "it": "Active",                                          "es": "Active",                                          "pl": "Active"},
    "addresses": {              "en": "addresses to monitoring",                         "de": "Adresse für Monitoring",                          "ru": "Список IP адресов для мониторинга",               "pt": "addresses to monitoring",                         "nl": "addresses to monitoring",                         "fr": "addresses to monitoring",                         "it": "addresses to monitoring",                         "es": "addresses to monitoring",                         "pl": "addresses to monitoring"},
    "interval": {               "en": "Polling interval (ms)",                           "de": "Abfrage Intervall (ms)",                          "ru": "Интервал опроса в миллисекундах:",                "pt": "Polling interval (ms)",                           "nl": "Polling interval (ms)",                           "fr": "Polling interval (ms)",                           "it": "Polling interval (ms)",                           "es": "Polling interval (ms)",                           "pl": "Polling interval (ms)"},
    "macaddress": {             "en": "Mac Address",                                     "de": "Mac Adresse",                                     "ru": "Mac Адрес",                                       "pt": "Mac Address",                                     "nl": "Mac Address",                                     "fr": "Mac Address",                                     "it": "Mac Address",                                     "es": "Mac Address",                                     "pl": "Mac Address"},
    "name": {                   "en": "Name",                                            "de": "Name",                                            "ru": "Имя",                                             "pt": "Name",                                            "nl": "Name",                                            "fr": "Name",                                            "it": "Name",                                            "es": "Name",                                            "pl": "Name"},
    "settings": {               "en": "Adapter settings",                                "de": "Adapter-Einstellungen",                           "ru": "Настройки драйвера",                              "pt": "Adapter settings",                                "nl": "Adapter settings",                                "fr": "Adapter settings",                                "it": "Adapter settings",                                "es": "Adapter settings",                                "pl": "Adapter settings"},
    "Asus User": {              "en": "Login User",                                      "de": "Login User",                                      "ru": "Логин пользователя",                              "pt": "Login User",                                      "nl": "Login User",                                      "fr": "Login User",                                      "it": "Login User",                                      "es": "Login User",                                      "pl": "Login User"},
    "Asus Password": {          "en": "Login Password",                                  "de": "Login Passwort",                                  "ru": "Логин Пароль",                                    "pt": "Login Password",                                  "nl": "Login Password",                                  "fr": "Login Password",                                  "it": "Login Password",                                  "es": "Login Password",                                  "pl": "Login Password"},
    "Asus IP": {                "en": "Asus Router IP-Address",                          "de": "Asus Router IP-Adresse",                          "ru": "Asus IP-адрес маршрутизатора",                    "pt": "Asus Router IP-Adresse",                          "nl": "Asus Router IP-Adresse",                          "fr": "Asus Router IP-Adresse",                          "it": "Asus Router IP-Adresse",                          "es": "Asus Router IP-Adresse",                          "pl": "Asus Router IP-Adresse"},
    "Enabled": {                "en": "Device Polling Enabled",                          "de": "Gerät Prüfung aktiviert",                         "ru": "опрос устройства включен",                        "pt": "Device Polling Enabled",                          "nl": "Device Polling Enabled",                          "fr": "Device Polling Enabled",                          "it": "Device Polling Enabled",                          "es": "Device Polling Enabled",                          "pl": "Device Polling Enabled"},
    "SSH Port": {               "en": "SSH Port (Standard 22)",                          "de": "SSH Port (Standard 22)",                          "ru": "Порт SSH (Стандарт 22)",                          "pt": "SSH Port (Standard 22)",                          "nl": "SSH Port (Standard 22)",                          "fr": "SSH Port (Standard 22)",                          "it": "SSH Port (Standard 22)",                          "es": "SSH Port (Standard 22)",                          "pl": "SSH Port (Standard 22)"},          
    "ssh_type": {               "en": "SSH Type (see Readme)",                           "de": "SSH Typ (siehe Readme)",                          "ru": "Тип SSH (смотри readme)",                         "pt": "SSH Type (see Readme)",                           "nl": "SSH Type (see Readme)",                           "fr": "SSH Type (see Readme)",                           "it": "SSH Type (see Readme)",                           "es": "SSH Type (see Readme)",                           "pl": "SSH Type (see Readme)"},
    "Active Interval": {        
        "en": "Time Device is not active Anymore (ms)",
        "de": "Zeit bis wann das Gerät als Abesend markiert wird (ms)",
        "ru": "Устройство времени больше не активно (ms)",
        "pt": "Time Device is not active Anymore (ms)",
        "nl": "Time Device is not active Anymore (ms)",
        "fr": "Time Device is not active Anymore (ms)",
        "it": "Time Device is not active Anymore (ms)",
        "es": "Time Device is not active Anymore (ms)",
        "pl": "Time Device is not active Anymore (ms)"
    }
};