/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "active": {                 "en": "Active",                                          "de": "Aktiviert",                                       "ru": "Актив",                                           "pt": "Active",                                          "nl": "Active",                                          "fr": "Active",                                          "it": "Active",                                          "es": "Active",                                          "pl": "Active"},
    "addresses": {              "en": "addresses to monitoring",                         "de": "Adresse für Monitoring",                          "ru": "Список IP адресов для мониторинга",               "pt": "addresses to monitoring",                         "nl": "addresses to monitoring",                         "fr": "addresses to monitoring",                         "it": "addresses to monitoring",                         "es": "addresses to monitoring",                         "pl": "addresses to monitoring"},
    "interval": {               "en": "Polling interval (ms)",                           "de": "Abfrage Intervall (ms)",                          "ru": "Интервал опроса в миллисекундах:",                "pt": "Polling interval (ms)",                           "nl": "Polling interval (ms)",                           "fr": "Polling interval (ms)",                           "it": "Polling interval (ms)",                           "es": "Polling interval (ms)",                           "pl": "Polling interval (ms)"},
    "macaddress": {             "en": "Mac Address",                                     "de": "Mac Adresse",                                     "ru": "Mac Адрес",                                       "pt": "Mac Address",                                     "nl": "IP Address",                                      "fr": "IP Address",                                      "it": "IP Address",                                      "es": "IP Address",                                      "pl": "Mac Address"},
    "name": {                   "en": "Name",                                            "de": "Name",                                            "ru": "Имя",                                             "pt": "Name",                                            "nl": "Name",                                            "fr": "Name",                                            "it": "Name",                                            "es": "Name",                                            "pl": "Name"},
    "settings": {               "en": "Adapter settings",                                "de": "Adapter-Einstellungen",                           "ru": "Настройки драйвера",                              "pt": "Adapter settings",                                "nl": "Adapter settings",                                "fr": "Adapter settings",                                "it": "Adapter settings",                                "es": "Adapter settings",                                "pl": "Adapter settings"},
    "Asus User": {              "en": "Login User",                                      "de": "Login User"},
    "Asus Password": {          "en": "Login Password",                                  "de": "Login Passwort"},
    "Asus IP": {                "en": "Asus Router IP-Address",                          "de": "Asus Router IP-Adresse"},
    "Active Interval": {        "en": "Time Device not active Anymor (ms)",              "de": "Zeit bis wann das Gerät als Abesend markiert wird (ms)"},
    "Enabled": {                "en": "Device Polling Enabled",                          "de": "Gerät Prüfung aktiviert"},
    "SSH Port": {               "en": "SSH Port (Standard 22)",                          "de": "SSH Port (Standard 22)"}           
};